config/routes.rb
Rails.application.routes.draw do

  resources :feeds do
    collection do
      post :confirm
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  root to: "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/feed.rb
class Feed < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  validates :message, presence: true, if: -> { image.blank? }
  validates :image, presence: true, if: -> { message.blank? }

  def user
    return User.find_by(id: self.user_id)
  end


end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: {maximum:30}
  validates :email, presence: true, length: {maximum:255},
              format: {with:/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i},
              uniqueness:true
  before_validation { email.downcase! }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :feeds
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  def index
    @feeds = Feed.all.order(created_at: :desc)
  end

  def show
  end

  def new
    if params[:back]
    @feed = Feed.new(feed_params)
    else
    @feed = Feed.new
    end
  end

  def confirm
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id

    render :new if @feed.invalid?
  end

  def edit
  end

  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id
      respond_to do |format|
        if @feed.save
          format.html { redirect_to @feed, notice: '投稿されました' }
          format.json { render :show, status: :created, location: @feed }
        else
          format.html { render :new }
          format.json { render json: @feed.errors, status: :unprocessable_entity }
        end
      end
  end

  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: '更新されました' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: '削除されました.' }
      format.json { head :no_content }
    end
  end

############################################################
  private

  def set_feed
   @feed = Feed.find(params[:id])
  end


  def feed_params
    params.require(:feed).permit(:image, :message, :image_cache)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email:params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:notice] = "ログインしました"
      redirect_to user_path(user.id)

    else
      flash.now[:danger] = "ログインに失敗しました"
      render "new"
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "ログアウトしました"
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "登録しました"  #？？？#
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end


  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation,
    :birthday, :gender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end


 def logged_in?
   current_user.present?
 end

 def destroy
   session.delete(:user_id)
   flash[:notice] = 'ログアウトしました'
   redirect_to new_session_path
 end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/feeds/_form.html.erb
<div class="feeds_container">

  <%= form_with(model: feed, local: true,  url:confirm_feeds_path) do |form| %>
      <% if feed.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
          <ul>
          <% feed.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <div class="field">
      <%= form.label :写真 %>
      <%= image_tag(@feed.image.thumb.url) if @feed.image && @feed.image.url %>
      <%= form.file_field :image %>
      <%= form.text_area :message,size: "50x5",placeholder:"メッセージを入力" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
    <%= link_to '投稿一覧に戻る', feeds_path %>

</div>

app/views/feeds/confirm.html.erb
<div class="feeds_container">
  <h1>確認画面</h1>
  <%= form_with(model: @feed, url: feeds_path, local: true) do |form| %>
    <%= image_tag(@feed.image.thumb.url) if @feed.image && @feed.image.url %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :message %>
      <p> <%= @feed.message %>  </p>
    <%= form.submit "投稿する" %>
  <% end %>

  <%= form_with(model:@feed, url:new_feed_path, local:true, method:"get") do |form| %>
    <%= form.hidden_field :image_cache %>
    <%= form.hidden_field :message %>
    <%= form.submit "戻る", name: "back" %>
  <% end %>
</div>

app/views/feeds/edit.html.erb
<div class="feeds_container">
  <h1>編集する</h1>
  <%= form_with(model: @feed, local: true) do |form| %>
      <% if @feed.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(feed.errors.count, "error") %> prohibited this feed from being saved:</h2>
          <ul>
          <% @feed.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

    <div class="field">
      <%= form.label :写真 %>
      <%= image_tag(@feed.image.thumb.url) if @feed.image && @feed.image.url %>
      <br />
      <%= form.file_field :image %>
      <%= form.text_area :message,size: "50x4",placeholder:"メッセージを入力" %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
   <%= link_to '投稿一覧に戻る', feeds_path %>

</div>

app/views/feeds/index.html.erb
<div class="feeds_container">

  <h2><%= link_to '新しく投稿する', new_feed_path %></h2>
  <br />
  <br />
  <h1>投稿一覧</h1>

  <div class="post">
    <% @feeds.each do |feed| %>
        <p><%= image_tag(feed.image.thumb.url) if feed.image.present? %></p>
        <p><%= feed.message %></p>
        <p><%= feed.user.name %>が投稿 </p>
        <p><%= feed.updated_at %>に投稿</p>
        <td><%= link_to '詳細', feed %></td>
        <td><%= link_to '編集', edit_feed_path(feed) %></td>
        <td><%= link_to '削除', feed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <br><br>
        <span>---------------------------------------------------------</span>
    <% end %>
  </div>

</div>

app/views/feeds/new.html.erb
  <h1>新規投稿</h1>
  <%= render 'form', feed: @feed %>

app/views/feeds/show.html.erb
<div class="feeds_container">
  <p id="notice"><%= notice %></p>
    <strong>写真:</strong>
  <p>
    <%= image_tag @feed.image.thumb.url if @feed.image.present? %>
  </p>
  <p><%= @feed.message %> </p>
  <%= link_to '編集する', edit_feed_path(@feed) %> |
  <%= link_to '投稿一覧に戻る', feeds_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FacebookKadai</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <div class="wrapper">

      <header>
          <% flash.each do |key, value| %>
            <%= content_tag(:div, value, class: "#{key}") %>
          <% end %>
        <div class="header-logo">
          <h3>Facebook-clone課題</h3>
        </div>

        <div class="header-menu">
          <ul>
            <% if logged_in? %>
              <li>現在ログイン中のユーザー：<%= current_user.name %></li>
              <li><%= link_to "Profile", user_path(current_user.id),:style=>"color:white;" %></li>
              <li><%= link_to "Logout", session_path(current_user.id), method: :delete,:style=>"color:white;" %></li>
            <% else %>
              <li><%= link_to "Sign up", new_user_path ,:style=>"color:white;" %></li>
              <li><%= link_to "Login", new_session_path,:style=>"color:white;" %></li>
            <% end %>
          </ul>
        </div>
      </header>

      <div class = "container">
        <%= yield %>
      </div>

      <footer>
        <div class="footer-logo">
          <p> DIC課題</p>
        </div>
        <div class="footer-myname">
          <p>小林智彦</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="new_message">
  <h3>Facebookを使うと、友達や同僚、同級生、仲間たちとつながりを深められます。
    ケータイ、スマートフォンからもアクセスできます。</h3>
  <%= image_tag "D2gpTO7NG8Y.png", size:"500x200" %>
</div>

<div class="register_container">
  <h1>アカウント登録</h1>
  <h3>簡単に登録できます</h3>

  <%= form_with(model: @user, local: true) do |f| %>
    <div class="form">
      <%= f.label :名前 %>
      <%= f.text_field :name,placeholder: "姓名" %>
    </div>
    <br><br>
    <div class="form">
      <%= f.label :アドレス %>
      <%= f.email_field :email,placeholder: "xxx@example.com"%>
    </div>
    <br><br>
    <div class="form">
      <%= f.label :パスワード %>
      <%= f.password_field :password ,placeholder: "パスワードを設定"%>
    </div>
    <br><br>
    <div class="form">
      <%= f.label :パスワード確認用 %>
      <%= f.password_field :password_confirmation,placeholder: "パスワードをもう一度入力してください" %>
    </div>
    <br><br>
    <div class="form">
      <%=f.label :誕生日 %>

      <%= f.date_select(
            :birthday,
            start_year: 1930,
            end_year: (Time.now.year - 18),
            default: Date.new(1989, 1, 1)) %>
    </div>

    <br><br>
    <div class="form">
      <span>性別&nbsp;&nbsp;</span>
      <%= f.label :gender, :男%>
      <%= f.radio_button :gender, 1 %>
      <%= f.label :gender, :女 %>
      <%= f.radio_button :gender, 2 %>
      <%= f.label :gender, :他 %>
      <%= f.radio_button :gender, 3 %>
    </div>
    <br><br>

    <div class="form">
      <%= f.submit "アカウント登録" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="users_show_container">

  <% if logged_in? %>
    <h1><%= @user.name %>のページ</h1>
  <%else%>
    <h1>ユーザー：<%= @user.name %>を登録しました。</h1>
    <h1>ログインしてください</h1>
  <%end %>

  <p>メールアドレス: <%= @user.email %></p>
  <p>生年月日：<%= @user.birthday %>  </p>
  <% if @user.gender =="1" %>
    <p>性別：男</p>
  <% elsif @user.gender =="2"%>
    <p>性別：女</p>
  <%else%>
    <p>性別：その他</p>
  <% end %>

  <% if logged_in? %>
    <p><%= link_to '投稿一覧へ', feeds_path %></p>
  <%else%>
  <%end %>

</div>